[project]
name = "weather"
version = "0.1.0"
description = "A sample weather MCP server using the NWS weather API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
]
